spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: root
    timeout: 3600
    jedis:
      pool:
        max-active: 100         #连接池最大连接数，负数表示没有限制
        max-wait: -1            #连接池最大阻塞等待时间
        max-idle: 20             #连接池最大空闲数
        min-idle: 5              #连接池最小空闲数
        shutdown-timeout: 3000     #jedis连接超时
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
      max-connections: 10
server:
  port: 8081
  servlet:
    context-path: /demo
logging:
  level:
    org.springframework: info
    com.example: debug
config:
  userName: abc123
  passWord : 12345678
